name: Send Discord Messages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  send-messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        python main.py
